/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton, SignOutButton, UserButton, useUser } from "@clerk/nextjs";
import Home1 from "./Home";
import Script from "next/script";

const CreatePostWizard =  () => {
  const {user} = useUser();
  console.log(user);
  if(!user) return null;
  return (
    <div className="flex w-full gap-3">
      {/* <img className="h-14 w-14 rounded-full" src={user.profileImageUrl} alt="profile-pic" /> */}
      <input className="ml-6 grow bg-transparent outline-none" placeholder="Type some emojis!" />
    </div>
  )
};

export default function Home() {
  const user = useUser();
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const { data, isLoading } = api.posts.getAll.useQuery();
  if(isLoading) return (<div>Loading...</div>)
  if(!data) return (<div>Something went wrong</div>)
  // console.log(data); 
//   <script src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js" crossorigin></script>

// <script
//   src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js"
//   crossorigin></script>

// <script
//   src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js"
//   crossorigin></script>

// <script>var Alert = ReactBootstrap.Alert;</script>
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

            {!user.isSignedIn && <div className="flex justify-center"><SignInButton /></div> }
            {user.isSignedIn && 
            <div className="flex justify-center"><Home1 /></div>}
            
    </>
    
  );
}
