/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { UserButton, useUser } from "@clerk/nextjs";

export default function Home() {
  const user = useUser();

  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const {data} = api.posts.getAll.useQuery();
  // console.log(data); 
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div>
      <UserButton afterSignOutUrl="/"/>
    </div>
    <div>
      { data?.map((post) => (<div key={post.id}>{post.content}</div>) )}
    </div>
    </>
  );
}
